### PR TITLE
Update scripts from WingetUI

### PR DESCRIPTION
**Pull request by panther7**
* Need add string `{0} {0} {0} Contributors, please add your names/usernames separated by comas (for credit purposes)` for contributors.
* Need add new translators screen

All source codes are from WingetUI project.

### CODE REVIEW

**Comment by panther7** [comment]
Rebased

**Comment by panther7** [comment]
Any news?

**Comment by marticliment** [comment]
please see telegram

**Comment by Godwhitelight** [comment]
> please see telegram

whats ur telegram?

**Review by marticliment — APPROVED** [review]

**Pull request merged**
